### ISSUE TITLE
Not working... 

### ISSUE THREAD

**Issue by leoseccia** [micromata/generator-baumeister#69]
after `yo` I run `npm run tasks` and get this...

```
$ npm run tasks

> projName@1.0.0 tasks C:\Users\..\node source\projName
> ntl -d -o

√  Npm Task List - v3.0.0
? Select a task to run:       start › Builds for development, starts a webserver, watches for changes.

> projName@1.0.0 start C:\Users\..\node source\projName
> npm-run-all clean:dev handlebars --parallel handlebars:watch webpack:server eslint:watch stylelint:watch --silent

Could Not Find C:\Users\..\node source\projName\.webpack-assets.json
√  Finished Handlebars build after 254 ms

C:\Users\..\node source\projName\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\..\node source\projName\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at Object.<anonymous> (C:\Users\..\node source\projName\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projName@1.0.0 start: `npm-run-all clean:dev handlebars --parallel handlebars:watch webpack:server eslint:watch stylelint:watch --silent`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the projName@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\..\AppData\Roaming\npm-cache\_logs\2018-10-10T12_29_32_424Z-debug.log
×  Error building interactive interface
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projName@1.0.0 tasks: `ntl -d -o`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the projName@1.0.0 tasks script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\..\AppData\Roaming\npm-cache\_logs\2018-10-10T12_29_32_508Z-debug.log
```

**Comment by fcladera** [comment]
Same error here!

**Comment by leoseccia** [comment]
@mischah thanks for the workaround... it still does not work... :(

**Comment by mischah** [comment]
Mhmm. It worked on my machine. Maybe `webpack@4.19.0` needs a specific `webpack-cli` version as well? 🤔 

I hope to find some time in the next couple of days to address this issue in a proper way.
